### ISSUE TITLE
Demos do not work properly with 2017 Calliope mini

### ISSUE THREAD

**Issue by RalfEggert** [calliope-mini/calliope-demo#1]
We tried to re-activate the demo application on our 2017 Calliope mini and encountered some problems:

- the version v1.1 https://github.com/calliope-mini/calliope-demo/releases/download/v1.1/Calliope-Firmware-v1.1.hex starts and we can process the intro session with pressing A but when have to press B in the intro session nothing happens. 
- the version v2.0 https://github.com/calliope-mini/calliope-demo/releases/download/v2.0/firmware.hex does not work at all, nothing happens
- the english version v2.0 https://github.com/calliope-mini/calliope-demo/releases/download/v2.0-en/calliope-demo-2.0-en.hex works properly

**Comment by thinkberg** [comment]
Sorry, there was a misttake and I attached the wrong hex file. The correct hex file has been attached to the release now: https://github.com/calliope-mini/calliope-demo/releases/tag/v2.0
